"""our exercise id -> RepDB exercise (name_en). Entries marked NEW replace an exercise that has no equivalent in any repository."""
MAP = {
 'march':      ('Bodyweight Squat', 'NEW'),
 'armcirc':    ('Cross-Body Shoulder Stretch', 'NEW'),
 'jj':         ('Jumping Jacks', ''),
 'legswing':   ('Front-to-Back Leg Swing', ''),
 'highknee':   ('High Knees', ''),
 'buttkick':   ('Bodyweight Reverse Lunge', 'NEW'),
 'rope':       ('Jump Rope', ''),
 'squatjump':  ('Jump Squat', ''),
 'lungejump':  ('Plyo Lunge', ''),
 'walk':       ('Walking', ''),
 'jog':        ('Running', ''),
 'run':        ('Running', ''),
 'sprint':     ('Running', ''),
 'hang':       ('Dead Hang', ''),
 'kneeraise':  ('Hanging Knee Raise', ''),
 'cobra':      ('Cobra Stretch', ''),
 'child':      ("Child's Pose", ''),
 'catcow':     ('Cat-Cow', ''),
 'knees2chest':('Knee-to-Chest Stretch', ''),
 'elongate':   ('Supine Spinal Twist', 'NEW'),
 'plank':      ('Plank', ''),
 'mclimb':     ('Mountain Climbers', ''),
 'burpee':     ('Burpees', ''),
 'wallangel':  ('Wall Push Ups', 'NEW'),
 'wallstand':  ('Mountain Pose', 'NEW'),
 'reach':      ('Standing Forward Fold', 'NEW'),
 'deadbug':    ('Dead Bug', ''),
 'birddog':    ('Bird-Dog', ''),
 'superman':   ('Superman', ''),
 'bridge':     ('Glute Bridge', ''),
 'calf':       ('Standing Calf Stretch', ''),
 'quadstretch':('Standing Quad Stretch', ''),
 'hipflex':    ('Kneeling Hip Flexor Stretch', ''),
 'hamfold':    ('Seated Forward Fold', ''),
 'sidebend':   ('Standing Side Bend', ''),
 'chestopen':  ('Doorway Chest Stretch', ''),
}
