import sys, json, math, os, datetime
sys.path.insert(0,'.')
import ex1, ex2, ex3
import overrides1
import overrides2
import overrides3
from build import EX, prepare
from figure import FLOOR

OUT = "/home/claude/grow/app/src/main/assets"
os.makedirs(OUT, exist_ok=True)

def r(v, n=3): return round(float(v), n)

exs = []
index = {}
for e in EX:
    out, s, pr = prepare(e)
    poses = []
    for Q in out:
        poses.append([r(Q["hip"][0]), r(Q["hip"][1]), r(Q["t"],1), r(Q["h"],1), r(Q["hf"]*s,4),
                      r(Q["un"],1), r(Q["fn"],1), r(Q["uf"],1), r(Q["ff"],1),
                      r(Q["tn"],1), r(Q["sn"],1), r(Q["tf"],1), r(Q["sf"],1),
                      r(Q["jaw"],1), r(Q["fo"],1), r(Q["fof"],1), (-999 if Q.get("rope") is None else r(Q["rope"],1)),
                      r(Q["kn"],2), r(Q["kf"],2), r(Q["cn"],2), r(Q["cf"],2)])
    ES = json.load(open("es.json"))
    d = dict(id=e["id"], n=e["name"].replace("-"," "), es=ES[e["id"]][0], d=ES[e["id"]][1], t=ES[e["id"]][2], p=e["pillar"], m=e["met"], sd=int(e["sided"]), lv=e["lvl"],
             lp=e["loop"], ez=e["ease"], fr=int(e["front"]), bu=int(e["bust"]), sc=r(s,3),
             bar=(r(pr["bar"],3) if "bar" in pr else -1), wall=(r(pr["wall"],3) if "wall" in pr else -1),
             mat=(pr["mat"] if "mat" in pr else None), rp=int(e["rope"]), ps=poses)
    index[e["id"]] = len(exs)
    exs.append(d)
json.dump(exs, open(os.path.join(OUT,"exercises.json"),"w"), separators=(",",":"), ensure_ascii=False)
print("exercises", len(exs), "bytes", os.path.getsize(os.path.join(OUT,"exercises.json")))

# the day-by-day plans are generated by plan_gen.py (plan.txt) and keep jaw.txt untouched
print('exercises exported')
